Repository Club-PARD/My_Precious_WEB, pull requests merged in 2023-12, with the labels that each got.

#8 구글 로그인 구현
  my_precious_project/src/API/Twilio.ts
  my_precious_project/src/API/googleLogin.js
  my_precious_project/src/App.js
  my_precious_project/src/Page/loginPage.js
  my_precious_project/src/contexts/ThemeContext.js.js
Labels: Feature

#9 파이어베이스 크리덴셜 숨김
  my_precious_project/.gitignore
  my_precious_project/src/API/googleLogin.js
Labels: Feature

#10 휴대폰 인증 구현
  my_precious_project/src/API/googleLogin.js
  my_precious_project/src/App.js
  my_precious_project/src/Page/loginPage.js
Labels: Feature

#11 필요없는 주석 삭제
  my_precious_project/src/Page/loginPage.js
Labels: Feature

#12 휴대폰 인증 코드파일명 변경
  my_precious_project/src/App.js
  my_precious_project/src/Page/loginfeat.js
Labels: Refactor

#13 Mj branch
  my_precious_project/src/App.js
  my_precious_project/src/Components/Web/Web_Home_Components/Weblogin.js
  my_precious_project/src/Page/LoginPage.js
  my_precious_project/src/Page/loginfeat.js
Labels: Refactor

#14 body에 있는 margin 0으로 변경
  my_precious_project/package-lock.json
  my_precious_project/package.json
  my_precious_project/public/index.html
  my_precious_project/src/Components/Web/Web_Home_Components/Weblogin.js
  my_precious_project/src/Page/LoginPage.js
Labels: Style

#15 로그인 기능 페이지 구성
  my_precious_project/src/Components/Web/Web_Login_Components/Weblogin_1.js
  my_precious_project/src/Components/Web/Web_Login_Components/Weblogin_2.js
  my_precious_project/src/Components/Web/Web_Login_Components/Weblogin_3.js
  my_precious_project/src/Page/LoginPage.js
Labels: Refactor

#16 닷컴포넌트 추가&웹로그인1 ui 구현
  my_precious_project/src/Components/Web/Web_Login_Components/DotButton.js
  my_precious_project/src/Components/Web/Web_Login_Components/Weblogin_1.js
Labels: Style

#17 WebLogin_2, WebLogin_3 UI 완성 및 DotButton 라우팅 설정
  my_precious_project/package-lock.json
  my_precious_project/package.json
  my_precious_project/src/API/googleLogin.js
  my_precious_project/src/App.js
  my_precious_project/src/Components/Web/Web_Home_Components/Webhome.js
  my_precious_project/src/Components/Web/Web_Login_Components/DotButton.js
  my_precious_project/src/Components/Web/Web_Login_Components/Weblogin_1.js
  my_precious_project/src/Components/Web/Web_Login_Components/Weblogin_2.js
  my_precious_project/src/Components/Web/Web_Login_Components/Weblogin_3.js
  my_precious_project/src/Page/LoginPage.js
  my_precious_project/src/Page/loginfeat.js
Labels: Style, Refactor

#18 Mj branch
  my_precious_project/src/API/firebaseAPI.js
  my_precious_project/src/API/googleLogin.js
  my_precious_project/src/API/phoneAuth.js
  my_precious_project/src/App.js
  my_precious_project/src/Components/Web/Web_Login_Components/Weblogin_1.js
  my_precious_project/src/Components/Web/Web_Login_Components/Weblogin_2.js
  my_precious_project/src/Components/Web/Web_Login_Components/Weblogin_3.js
  my_precious_project/src/Page/LoginPage.js
  my_precious_project/src/Page/loginfeat.js
Labels: Feature, API, Refactor

#20 WebLogin_1 css 변경&제출 버튼 기능 추가
  my_precious_project/src/Components/Web/Web_Login_Components/Weblogin_1.js
  my_precious_project/src/Components/Web/Web_Login_Components/Weblogin_2_checked.js
  my_precious_project/src/Components/Web/Web_Login_Components/Weblogin_3.js
Labels: Feature, Style, Refactor

#21 Request 페이지 생성 및 구조화
  my_precious_project/src/App.js
  my_precious_project/src/Components/Web/Layout_Components/Mypage_header.js
  my_precious_project/src/Components/Web/Web_Login_Components/Weblogin_1.js
  my_precious_project/src/Components/Web/Web_Login_Components/Weblogin_3.js
  my_precious_project/src/Page/RequestPage.js
Labels: Style

#23 대시보드 페이지 생성&대시보드 카드 컴포넌트 추가
  my_precious_project/src/App.js
  my_precious_project/src/Assets/img/Money.png
  my_precious_project/src/Components/App/App_Dashboard_Components/AppDashboard.js
  my_precious_project/src/Components/Web/Layout_Components/Mypage_header.js
  my_precious_project/src/Components/Web/Web_Dashboard_Components/CountUpAnimation.js
  my_precious_project/src/Components/Web/Web_Dashboard_Components/DashboardList.js
  my_precious_project/src/Components/Web/Web_Dashboard_Components/HistoryCard.js
  my_precious_project/src/Components/Web/Web_Dashboard_Components/WebDashboard.js
  my_precious_project/src/Page/DashboardPage.js
Labels: Feature, Style, Refactor

#22 231226 : 모달창 구현 완료 및 휴대폰 인증 성공 유무에 따라 화면 동작 처리 완료
  my_precious_project/package-lock.json
  my_precious_project/package.json
  my_precious_project/src/API/firebaseAPI.js
  my_precious_project/src/API/phoneAuth.js
  my_precious_project/src/App.js
  my_precious_project/src/Components/Web/Web_Login_Components/Modal/Modal.js
  my_precious_project/src/Components/Web/Web_Login_Components/Weblogin_1.js
  my_precious_project/src/Components/Web/Web_Login_Components/Weblogin_2.js
  my_precious_project/src/Components/Web/Web_Login_Components/Weblogin_2_checked.js
  my_precious_project/src/Components/Web/Web_Login_Components/Weblogin_3.js
  my_precious_project/src/Page/LoginPage.js
  my_precious_project/src/Page/loginfeat.js
Labels: Feature, Style, Refactor

#24 HistoryCard 호버시 css 변경
  my_precious_project/src/API/googleLogin.js
  my_precious_project/src/Assets/img/Userheart.png
  my_precious_project/src/Components/Web/Layout_Components/Mypage_header.js
  my_precious_project/src/Components/Web/Web_Dashboard_Components/HistoryCard.js
  my_precious_project/src/Components/Web/Web_Dashboard_Components/WebDashboard.js
  my_precious_project/src/Components/Web/Web_Login_Components/DotButton.js
  my_precious_project/src/Components/Web/Web_Login_Components/Googlelogin.js
  my_precious_project/src/Components/Web/Web_Login_Components/Weblogin_1.js
  my_precious_project/src/Components/Web/Web_Login_Components/Weblogin_2.js
  my_precious_project/src/Components/Web/Web_Login_Components/Weblogin_2_checked.js
  my_precious_project/src/Page/LoginPage.js
  my_precious_project/src/Style/theme.js
Labels: Style

#26 231228 : 구글로그인 수정 및 대시보드 2차 완성
  .DS_Store
  my_precious_project/package-lock.json
  my_precious_project/package.json
  my_precious_project/src/API/googleLogin.js
  my_precious_project/src/App.js
  my_precious_project/src/Assets/img/Money.png
  my_precious_project/src/Assets/img/Money.svg
  my_precious_project/src/Components/Web/Web_Dashboard_Components/ButtonMenu.js
  my_precious_project/src/Components/Web/Web_Dashboard_Components/CircleProgressbar.js
  my_precious_project/src/Components/Web/Web_Dashboard_Components/CountUpAnimation.js
  my_precious_project/src/Components/Web/Web_Dashboard_Components/DashboardList.js
  my_precious_project/src/Components/Web/Web_Dashboard_Components/DetailsBorrowMoney.js
  my_precious_project/src/Components/Web/Web_Dashboard_Components/DetailsReceiveMoney.js
  my_precious_project/src/Components/Web/Web_Dashboard_Components/DetailsTransaction.js
  my_precious_project/src/Components/Web/Web_Dashboard_Components/HistoryCard.js
  my_precious_project/src/Components/Web/Web_Dashboard_Components/WebDashboard.js
  my_precious_project/src/Components/Web/Web_Login_Components/Googlelogin.js
  my_precious_project/src/contexts/userContext.js
Labels: Feature, Style, Refactor

#25 로그인 페이지&헤더 레이아웃 px값 rem으로 변경 완료
  my_precious_project/package-lock.json
  my_precious_project/package.json
  my_precious_project/src/App.js
  my_precious_project/src/Assets/img/CheckBox.svg
  my_precious_project/src/Assets/img/Talk.svg
  my_precious_project/src/Components/App/App_RequestDetail_Components/AppRequestDetail.js
  my_precious_project/src/Components/Web/Layout_Components/Mypage_header.js
  my_precious_project/src/Components/Web/Web_Dashboard_Components/WebDashboard.js
  my_precious_project/src/Components/Web/Web_Login_Components/DotButton.js
  my_precious_project/src/Components/Web/Web_Login_Components/Weblogin_1.js
  my_precious_project/src/Components/Web/Web_Login_Components/Weblogin_2.js
  my_precious_project/src/Components/Web/Web_Login_Components/Weblogin_2_checked.js
  my_precious_project/src/Components/Web/Web_Login_Components/Weblogin_3.js
  my_precious_project/src/Components/Web/Web_RequestDetail_Components/BankSelect.js
  my_precious_project/src/Components/Web/Web_RequestDetail_Components/LeftSide.js
  my_precious_project/src/Components/Web/Web_RequestDetail_Components/LineProgress.js
  my_precious_project/src/Components/Web/Web_RequestDetail_Components/RightSide.js
  my_precious_project/src/Components/Web/Web_RequestDetail_Components/WebRequestDetail.js
  my_precious_project/src/Components/Web/Web_RequestDetail_Components/WritingMessage.js
  my_precious_project/src/Page/RequestDetailPage.js
Labels: Refactor

#28 요청 페이지 UI 구현 및 서버 연결
  my_precious_project/package-lock.json
  my_precious_project/package.json
  my_precious_project/public/img/RequestCharacter.svg
  my_precious_project/src/API/dummy.js
  my_precious_project/src/Assets/img/RequestShadow.svg
  my_precious_project/src/Components/Web/Web_Login_Components/Weblogin_2_checked.js
  my_precious_project/src/Page/RequestPage.js
Labels: Feature, Style, Refactor

#29 231230 민지 : 서버 연결 오류 해결 및 ui디테일 수정
  my_precious_project/package-lock.json
  my_precious_project/package.json
  my_precious_project/src/Page/RequestPage.js
Labels: Bug

#31 231230 민지 : 금액 콤마 오류 수정 및 충돌 해결
  my_precious_project/package-lock.json
  my_precious_project/src/Page/RequestPage.js
Labels: Bug

#32 231230 민지 : 금액 콤마 오류 수정
  my_precious_project/src/Page/RequestPage.js
Labels: Bug

#33 231231 : 대시보드 서버연결 중간완성
  my_precious_project/src/API/googleLogin.js
  my_precious_project/src/Components/Web/Web_Dashboard_Components/DashboardList.js
  my_precious_project/src/Components/Web/Web_Dashboard_Components/DetailsBorrowMoney.js
  my_precious_project/src/Components/Web/Web_Dashboard_Components/DetailsReceiveMoney.js
  my_precious_project/src/Components/Web/Web_Dashboard_Components/WebDashboard.js
  my_precious_project/src/Components/Web/Web_Login_Components/Googlelogin.js
  my_precious_project/src/Components/Web/Web_Login_Components/Weblogin_1.js
  my_precious_project/src/Components/Web/Web_Login_Components/Weblogin_2_checked.js
  my_precious_project/src/Components/Web/Web_Login_Components/Weblogin_3.js
Labels: API, Refactor

#34 231231 : API 충돌 해결
  my_precious_project/src/Components/Web/Web_Dashboard_Components/DashboardList.js
  my_precious_project/src/Components/Web/Web_Dashboard_Components/DetailsReceiveMoney.js
  my_precious_project/src/Components/Web/Web_Dashboard_Components/WebDashboard.js
  my_precious_project/src/Components/Web/Web_Login_Components/Weblogin_3.js
Labels: Bug, API

#35 231231 민지 : 요청페이지 라우팅 설정
  my_precious_project/public/img/CloseButton.svg
  my_precious_project/public/img/box.svg
  my_precious_project/public/img/checkbox.svg
  my_precious_project/src/API/googleLogin.js
  my_precious_project/src/Components/Web/Web_Dashboard_Components/DashboardList.js
  my_precious_project/src/Components/Web/Web_Dashboard_Components/WebDashboard.js
  my_precious_project/src/Components/Web/Web_Login_Components/Googlelogin.js
  my_precious_project/src/Components/Web/Web_Login_Components/Weblogin_1.js
  my_precious_project/src/Components/Web/Web_Login_Components/Weblogin_2_checked.js
  my_precious_project/src/Components/Web/Web_Login_Components/Weblogin_3.js
  my_precious_project/src/Page/.Rhistory
  my_precious_project/src/Page/RequestPage.js
Labels: Bug, Refactor

#38 231231 민지 : 요청페이지 ui및 서버 연결 구현
  my_precious_project/src/Page/RequestPage.js
Labels: Style, Refactor

#39 로그인 페이지&글읽기 페이지 이미지추가, 프로그레스바 상태에 따라 도와주기 버튼 비활성화 기능
  my_precious_project/src/Assets/img/Character.png
  my_precious_project/src/Components/Web/Web_Login_Components/Googlelogin.js
  my_precious_project/src/Components/Web/Web_Login_Components/Weblogin_1.js
  my_precious_project/src/Components/Web/Web_Login_Components/Weblogin_2.js
  my_precious_project/src/Components/Web/Web_Login_Components/Weblogin_3.js
  my_precious_project/src/Components/Web/Web_RequestDetail_Components/BankSelect.js
  my_precious_project/src/Components/Web/Web_RequestDetail_Components/LeftSide.js
  my_precious_project/src/Components/Web/Web_RequestDetail_Components/LineProgress.js
  my_precious_project/src/Components/Web/Web_RequestDetail_Components/RightSide.js
  my_precious_project/src/Components/Web/Web_RequestDetail_Components/WebRequestDetail.js
  my_precious_project/src/Components/Web/Web_RequestDetail_Components/WritingMessage.js
  my_precious_project/src/Style/theme.js
Labels: Feature, Style, Refactor
