Repository Club-PARD/My_Precious_WEB, pull requests merged in 2024-01, with the labels that each got.

#40 240101 민지 : 요청페이지 구현 완료
  my_precious_project/src/API/googleLogin.js
  my_precious_project/src/Components/Web/Web_Dashboard_Components/WebDashboard.js
  my_precious_project/src/Components/Web/Web_Login_Components/Googlelogin.js
  my_precious_project/src/Components/Web/Web_Login_Components/Modal/Modal.js
  my_precious_project/src/Components/Web/Web_Login_Components/Weblogin_2.js
  my_precious_project/src/Components/Web/Web_Login_Components/Weblogin_2_checked.js
  my_precious_project/src/Components/Web/Web_Login_Components/Weblogin_3.js
  my_precious_project/src/Page/RequestPage.js
Labels: Feature, Style, Refactor

#41 채권자 글읽기 페이지 ui&기능&서버연결 완료
  my_precious_project/package-lock.json
  my_precious_project/src/Assets/img/ImageX.png
  my_precious_project/src/Assets/img/ImageX.svg
  my_precious_project/src/Assets/img/Talk.svg
  my_precious_project/src/Components/Web/Web_RequestDetail_Components/CheckedMessage.js
  my_precious_project/src/Components/Web/Web_RequestDetail_Components/LeftSide.js
  my_precious_project/src/Components/Web/Web_RequestDetail_Components/Modal/SentToEmailModal.js
  my_precious_project/src/Components/Web/Web_RequestDetail_Components/RightSide.js
  my_precious_project/src/Components/Web/Web_RequestDetail_Components/WebRequestDetail.js
  my_precious_project/src/Components/Web/Web_RequestDetail_Components/WritingMessage.js
Labels: Feature, Style, Refactor

#49 240102 : 대시보드 배경색 잘림 버그 해결
  my_precious_project/package-lock.json
  my_precious_project/package.json
  my_precious_project/src/Components/Web/Web_Dashboard_Components/WebDashboard.js
  my_precious_project/src/Page/RequestPage.js
Labels: Style, Refactor

#51 240102 민지 : 해더 상단 고정
  my_precious_project/public/img/404_error.svg
  my_precious_project/public/img/Icon_back.svg
  my_precious_project/public/img/RequestCharacter.svg
  my_precious_project/src/API/firebaseAPI.js
  my_precious_project/src/Components/App/App_Request_Components/AppRequest.js
  my_precious_project/src/Components/Web/Layout_Components/Mypage_header.js
  my_precious_project/src/Components/Web/Web_Dashboard_Components/WebDashboard.js
  my_precious_project/src/Components/Web/Web_Login_Components/Modal/Modal.js
  my_precious_project/src/Components/Web/Web_Request_Components/WebRequest.js
  my_precious_project/src/Page/AboutPage.js
  my_precious_project/src/Page/DashboardPage.js
  my_precious_project/src/Page/HomePage.js
  my_precious_project/src/Page/LoginErrorPage.js
  my_precious_project/src/Page/LoginPage.js
  my_precious_project/src/Page/ManagePage.js
  my_precious_project/src/Page/RequestDetailPage.js
  my_precious_project/src/Page/RequestPage.js
  my_precious_project/src/Page/loginfeat.js
Labels: Style

#52 240102 현중 : 대시보드 서버 스키마에 맞게 수정 및 로그인 화면 CSS 동작 구현
  my_precious_project/package-lock.json
  my_precious_project/package.json
  my_precious_project/src/API/googleLogin.js
  my_precious_project/src/App.js
  my_precious_project/src/Components/Web/Web_Dashboard_Components/ButtonMenu.js
  my_precious_project/src/Components/Web/Web_Dashboard_Components/DashboardList.js
  my_precious_project/src/Components/Web/Web_Dashboard_Components/DetailsBorrowMoney.js
  my_precious_project/src/Components/Web/Web_Dashboard_Components/DetailsReceiveMoney.js
  my_precious_project/src/Components/Web/Web_Dashboard_Components/WebDashboard.js
  my_precious_project/src/Components/Web/Web_Login_Components/Googlelogin.js
  my_precious_project/src/Components/Web/Web_Login_Components/Weblogin_1.js
  my_precious_project/src/Components/Web/Web_Login_Components/Weblogin_2.js
  my_precious_project/src/Components/Web/Web_Login_Components/Weblogin_2_checked.js
  my_precious_project/src/Components/Web/Web_Login_Components/Weblogin_3.js
  my_precious_project/src/Components/Web/Web_ManageRequest_Components/DisplayFriend.js
  my_precious_project/src/Components/Web/Web_RequestDetail_Components/CheckedMessage.js
  my_precious_project/src/Components/Web/Web_RequestDetail_Components/Modal/SentToEmailModal.js
  my_precious_project/src/Components/Web/Web_RequestDetail_Components/RightSide.js
  my_precious_project/src/Components/Web/Web_RequestDetail_Components/WritingMessage.js
  my_precious_project/src/Page/RequestPage.js
  my_precious_project/src/contexts/userContext.js
Labels: Bug, Refactor

#54 240103 민지 : 해더 ui 수정
  my_precious_project/src/App.js
  my_precious_project/src/Components/Web/Layout_Components/Mypage_header.js
  my_precious_project/src/Components/Web/Web_Dashboard_Components/DetailsBorrowMoney.js
  my_precious_project/src/Components/Web/Web_Dashboard_Components/DetailsReceiveMoney.js
  my_precious_project/src/Components/Web/Web_Dashboard_Components/WebDashboard.js
  my_precious_project/src/Components/Web/Web_ManageRequest_Components/ManageSummary.js
  my_precious_project/src/Components/Web/Web_ManageRequest_Components/WebManageRequest.js
  my_precious_project/src/Components/Web/Web_RequestDetail_Components/LeftSide.js
  my_precious_project/src/Components/Web/Web_RequestDetail_Components/Modal/SentToEmailModal.js
  my_precious_project/src/Components/Web/Web_RequestDetail_Components/WebRequestDetail.js
  my_precious_project/src/Components/Web/Web_Request_Components/WebRequest.js
Labels: Style, Refactor

#55 240103 민지 : 요청페이지 ui 수정 완료
  my_precious_project/src/App.js
  my_precious_project/src/Components/Web/Web_Login_Components/Weblogin_1.js
  my_precious_project/src/Components/Web/Web_Login_Components/Weblogin_2.js
  my_precious_project/src/Components/Web/Web_Login_Components/Weblogin_2_checked.js
  my_precious_project/src/Components/Web/Web_Login_Components/Weblogin_3.js
  my_precious_project/src/Components/Web/Web_ManageRequest_Components/ManageBottom.js
  my_precious_project/src/Components/Web/Web_ManageRequest_Components/ShowMyboard.js
  my_precious_project/src/Components/Web/Web_RequestDetail_Components/Modal/SentToEmailModal.js
  my_precious_project/src/Components/Web/Web_Request_Components/WebRequest.js
  my_precious_project/src/Page/RequestPage.js
  my_precious_project/src/contexts/userContext.js
Labels: Style, Refactor

#56 240103 민지 : manage_request 페이지 서버 연결 오류 해결
  my_precious_project/src/Components/Web/Web_ManageRequest_Components/ManageBottom.js
Labels: Bug, Refactor

#57 230103 민지 : ShowMyboard.js 서버 오류 수정 및 ui 수정 완료
  my_precious_project/src/Components/Web/Web_ManageRequest_Components/ShowMyboard.js
Labels: Bug, Style, Refactor

#60 240103 현중 : 프로그레스바 오류 해결
  my_precious_project/src/Components/Web/Web_Dashboard_Components/CircleProgressbar.js
Labels: Bug

#62 240103 민지 : manage-request 서버 연결 오류 수정
  my_precious_project/src/Components/Web/Web_ManageRequest_Components/DisplayFriend.js
  my_precious_project/src/Components/Web/Web_ManageRequest_Components/ManageBottom.js
  my_precious_project/src/Components/Web/Web_ManageRequest_Components/ManageFriendList.js
  my_precious_project/src/Components/Web/Web_ManageRequest_Components/ManageSummary.js
  my_precious_project/src/Components/Web/Web_ManageRequest_Components/ShowMyboard.js
  my_precious_project/src/Components/Web/Web_ManageRequest_Components/WebManageRequest.js
  my_precious_project/src/Components/Web/Web_RequestDetail_Components/LeftSide.js
  my_precious_project/src/Components/Web/Web_Request_Components/WebRequest.js
Labels: Bug

#58 헤더 대시보드 클릭시 대시보드로 이동되도록 라우팅
  my_precious_project/src/Components/Web/Layout_Components/Mypage_header.js
  my_precious_project/src/Components/Web/Web_ManageRequest_Components/ManageFriendList.js
  my_precious_project/src/Components/Web/Web_ManageRequest_Components/WebManageRequest.js
  my_precious_project/src/Components/Web/Web_RequestDetail_Components/CheckedMessage.js
  my_precious_project/src/Components/Web/Web_RequestDetail_Components/LeftSide.js
  my_precious_project/src/Components/Web/Web_RequestDetail_Components/LineProgress.js
  my_precious_project/src/Components/Web/Web_RequestDetail_Components/Modal/SentToEmailModal.js
  my_precious_project/src/Components/Web/Web_RequestDetail_Components/RightSide.js
  my_precious_project/src/Components/Web/Web_RequestDetail_Components/WebRequestDetail.js
  my_precious_project/src/Components/Web/Web_RequestDetail_Components/WritingMessage.js
Labels: Feature

#63 240103 민지 : request-detail 페이지 서버 연결 구현
  my_precious_project/src/Components/Web/Web_ManageRequest_Components/ManageFriendList.js
  my_precious_project/src/Components/Web/Web_RequestDetail_Components/LeftSide.js
  my_precious_project/src/Components/Web/Web_RequestDetail_Components/WebRequestDetail.js
Labels: Bug, Refactor

#64 240103 민지 : 서버 버전 변경
  my_precious_project/src/API/googleLogin.js
  my_precious_project/src/Components/Web/Web_Dashboard_Components/WebDashboard.js
  my_precious_project/src/Components/Web/Web_Login_Components/Googlelogin.js
  my_precious_project/src/Components/Web/Web_Login_Components/Weblogin_2_checked.js
  my_precious_project/src/Components/Web/Web_Login_Components/Weblogin_3.js
  my_precious_project/src/Components/Web/Web_ManageRequest_Components/DisplayFriend.js
  my_precious_project/src/Components/Web/Web_ManageRequest_Components/ManageBottom.js
  my_precious_project/src/Components/Web/Web_ManageRequest_Components/ManageFriendList.js
  my_precious_project/src/Components/Web/Web_ManageRequest_Components/ManageSummary.js
  my_precious_project/src/Components/Web/Web_ManageRequest_Components/WebManageRequest.js
  my_precious_project/src/Components/Web/Web_RequestDetail_Components/CheckedMessage.js
  my_precious_project/src/Components/Web/Web_RequestDetail_Components/LeftSide.js
  my_precious_project/src/Components/Web/Web_RequestDetail_Components/Modal/SentToEmailModal.js
  my_precious_project/src/Components/Web/Web_RequestDetail_Components/RightSide.js
  my_precious_project/src/Components/Web/Web_RequestDetail_Components/WritingMessage.js
  my_precious_project/src/Components/Web/Web_Request_Components/WebRequest.js
Labels: Deploy, Refactor

#65 240103 민지 : manage-request 돈을 갚았어요 버튼 수정 완료
  my_precious_project/src/Components/Web/Web_ManageRequest_Components/DisplayFriend.js
  my_precious_project/src/Components/Web/Web_RequestDetail_Components/Modal/SentToEmailModal.js
Labels: Bug

#67 240104 민지 : 깃 reset 공유
  my_precious_project/src/Components/Web/Web_Login_Components/Googlelogin.js
  my_precious_project/src/Components/Web/Web_Login_Components/Weblogin_3.js
  my_precious_project/src/Components/Web/Web_ManageRequest_Components/ManageFriendList.js
  my_precious_project/src/Components/Web/Web_ManageRequest_Components/WebManageRequest.js
  my_precious_project/src/Components/Web/Web_RequestDetail_Components/CheckedMessage.js
  my_precious_project/src/Components/Web/Web_RequestDetail_Components/LeftSide.js
  my_precious_project/src/Components/Web/Web_RequestDetail_Components/Modal/SentToEmailModal.js
  my_precious_project/src/Components/Web/Web_RequestDetail_Components/RightSide.js
  my_precious_project/src/Components/Web/Web_Request_Components/WebRequest.js
Labels: Refactor

#68 240104 민지 : 충돌 해결
  my_precious_project/src/Components/Web/Web_RequestDetail_Components/RightSide.js
Labels: Bug

#69 240104 민지 : 충돌 해결
  my_precious_project/src/Components/Web/Web_ManageRequest_Components/ManageFriendList.js
  my_precious_project/src/Components/Web/Web_RequestDetail_Components/CheckedMessage.js
Labels: Bug

#72 240105 현중 : Request 모달창 구현
  my_precious_project/src/Components/Web/Web_Login_Components/Modal/RequestModal.js
  my_precious_project/src/Components/Web/Web_Login_Components/Weblogin_2.js
  my_precious_project/src/Components/Web/Web_RequestDetail_Components/LeftSide.js
  my_precious_project/src/Components/Web/Web_Request_Components/WebRequest.js
Labels: Style, Refactor

#71 240105 유현 : 채권자 글읽기 페이지 오른쪽 화면 css 수정
  my_precious_project/src/Assets/img/BlueCharacter2.svg
  my_precious_project/src/Assets/img/Clock.svg
  my_precious_project/src/Assets/img/Paper.svg
  my_precious_project/src/Assets/img/Peaple.svg
  my_precious_project/src/Components/Web/Web_Login_Components/Googlelogin.js
  my_precious_project/src/Components/Web/Web_Login_Components/Weblogin_3.js
  my_precious_project/src/Components/Web/Web_ManageRequest_Components/DisplayFriend.js
  my_precious_project/src/Components/Web/Web_ManageRequest_Components/ManageBottom.js
  my_precious_project/src/Components/Web/Web_ManageRequest_Components/ManageFriendList.js
  my_precious_project/src/Components/Web/Web_ManageRequest_Components/ManageSummary.js
  my_precious_project/src/Components/Web/Web_ManageRequest_Components/ShowMyboard.js
  my_precious_project/src/Components/Web/Web_ManageRequest_Components/SmallLineProgress.js
  my_precious_project/src/Components/Web/Web_ManageRequest_Components/SummaryFriend.js
  my_precious_project/src/Components/Web/Web_ManageRequest_Components/WebManageRequest.js
  my_precious_project/src/Components/Web/Web_RequestDetail_Components/CheckedMessage.js
  my_precious_project/src/Components/Web/Web_RequestDetail_Components/Modal/SentToEmailModal.js
  my_precious_project/src/Components/Web/Web_RequestDetail_Components/RightSide.js
  my_precious_project/src/Components/Web/Web_RequestDetail_Components/WebRequestDetail.js
  my_precious_project/src/Components/Web/Web_RequestDetail_Components/WritingMessage.js
  my_precious_project/src/Components/Web/Web_Request_Components/WebRequest.js
Labels: Style

#73 240105 유현: 홈화면 레이아웃 추가
  my_precious_project/src/Assets/img/HomeTopImage.svg
  my_precious_project/src/Components/Web/Web_Home_Components/FirstHome.js
  my_precious_project/src/Components/Web/Web_Home_Components/Webhome.js
  my_precious_project/src/Components/Web/Web_ManageRequest_Components/DisplayFriend.js
  my_precious_project/src/Components/Web/Web_ManageRequest_Components/ManageBottom.js
  my_precious_project/src/Components/Web/Web_RequestDetail_Components/CheckedMessage.js
Labels: Style

#74 240105 민지 : 배포 성공
  my_precious_project/.firebase/hosting.YnVpbGQ.cache
  my_precious_project/package.json
  my_precious_project/public/img/box.svg
  my_precious_project/src/API/googleLogin.js
  my_precious_project/src/App.js
  my_precious_project/src/Components/Web/Web_Dashboard_Components/WebDashboard.js
  my_precious_project/src/Components/Web/Web_Login_Components/Googlelogin.js
  my_precious_project/src/Components/Web/Web_Login_Components/Weblogin_2_checked.js
  my_precious_project/src/Components/Web/Web_Login_Components/Weblogin_3.js
  my_precious_project/src/Components/Web/Web_ManageRequest_Components/DisplayFriend.js
  my_precious_project/src/Components/Web/Web_ManageRequest_Components/ManageBottom.js
  my_precious_project/src/Components/Web/Web_ManageRequest_Components/ManageFriendList.js
  my_precious_project/src/Components/Web/Web_ManageRequest_Components/ManageSummary.js
  my_precious_project/src/Components/Web/Web_ManageRequest_Components/ShowMyboard.js
  my_precious_project/src/Components/Web/Web_ManageRequest_Components/WebManageRequest.js
  my_precious_project/src/Components/Web/Web_RequestDetail_Components/CheckedMessage.js
  my_precious_project/src/Components/Web/Web_RequestDetail_Components/LeftSide.js
  my_precious_project/src/Components/Web/Web_RequestDetail_Components/LineProgress.js
  my_precious_project/src/Components/Web/Web_RequestDetail_Components/Modal/SentToEmailModal.js
  my_precious_project/src/Components/Web/Web_RequestDetail_Components/RightSide.js
  my_precious_project/src/Components/Web/Web_RequestDetail_Components/WebRequestDetail.js
  my_precious_project/src/Components/Web/Web_RequestDetail_Components/WritingMessage.js
  my_precious_project/src/Components/Web/Web_Request_Components/WebRequest.js
Labels: Deploy

#75 240105 민지 : 배포 링크 수정
  my_precious_project/.firebase/hosting.YnVpbGQ.cache
  my_precious_project/src/Components/Web/Web_ManageRequest_Components/ManageSummary.js
Labels: Bug, Deploy

#77 230106 유현: 채권자 글읽기 오른쪽 화면 로그인/비로그인 상황때 나타나는 화면 오류 수정
  my_precious_project/src/API/googleLogin.js
  my_precious_project/src/App.js
  my_precious_project/src/Components/Web/Layout_Components/Mypage_header.js
  my_precious_project/src/Components/Web/Web_Home_Components/HomeHeader.js
  my_precious_project/src/Components/Web/Web_Home_Components/Webhome.js
  my_precious_project/src/Components/Web/Web_Login_Components/Googlelogin.js
  my_precious_project/src/Components/Web/Web_Login_Components/Weblogin_3.js
  my_precious_project/src/Components/Web/Web_RequestDetail_Components/RightSide.js
  my_precious_project/src/Cursor.css
  my_precious_project/src/Cursor.js
  my_precious_project/src/contexts/userContext.js
Labels: Bug, Feature

#79 240106 민지 : 서버 연결 오류 해결
  my_precious_project/.firebase/hosting.YnVpbGQ.cache
  my_precious_project/public/index.html
  my_precious_project/public/main_logo.ico
  my_precious_project/src/Components/Web/Web_Dashboard_Components/DetailsReceiveMoney.js
  my_precious_project/src/Components/Web/Web_Dashboard_Components/WebDashboard.js
  my_precious_project/src/Components/Web/Web_ManageRequest_Components/DisplayFriend.js
  my_precious_project/src/Components/Web/Web_ManageRequest_Components/WebManageRequest.js
  my_precious_project/src/Components/Web/Web_RequestDetail_Components/CheckedMessage.js
  my_precious_project/src/Components/Web/Web_RequestDetail_Components/LeftSide.js
  my_precious_project/src/Components/Web/Web_RequestDetail_Components/RightSide.js
  my_precious_project/src/Components/Web/Web_RequestDetail_Components/WebRequestDetail.js
  my_precious_project/src/Components/Web/Web_Request_Components/WebRequest.js
Labels: Bug

#80 로그인 상태에 따른 헤더 데시보드 활성화여부&채권자 글읽기 페이지 오류 수정
  my_precious_project/src/Components/Web/Web_Home_Components/HomeHeader.js
  my_precious_project/src/Components/Web/Web_RequestDetail_Components/CheckedMessage.js
Labels: Bug
